name: Test Azure Deployment

permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:

jobs:
  test-azure:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_AKS_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_AKS_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_AKS_SUBSCRIPTION_ID }}

      - name: Find IP address of offer frontend load balancer
        run: |
          az aks get-credentials --resource-group tf-demo-offer-inc-rg --name tf-demo-offer-inc-aks --overwrite-existing
          OFE_IP=$(kubectl get svc ofe-lb -n default -o jsonpath="{.status.loadBalancer.ingress[0].ip}")
          echo "OFE_IP=$OFE_IP" >> $GITHUB_ENV

      - name: Run secure invoke
        env:
          KMS_URL: "https://depa-inferencing-kms.centralindia.cloudapp.azure.com"
        working-directory: ./tools/secure-invoke
        run: |
          REQUESTS_DIR=${GITHUB_WORKSPACE}/tools/requests
          sed -i 's|/home/azureuser/requests|'"$REQUESTS_DIR"'|g' ./.env
          sed -i 's|<KMS_HOST>|'"$KMS_URL"'|g' ./.env
          sed -i 's|<hostname>|'"$OFE_IP"'|g' ./.env
          sed -i '/CA_CERT/d' ./.env
          sed -i '/CLIENT_CERT/d' ./.env
          sed -i '/CLIENT_KEY/d' ./.env
          ./secure_invoke_test.sh
